_BASE_: ../coco-stuff-164k-171/maskformer_R50_bs32_60k.yaml
ORACLE: True
MODEL:
  WEIGHTS: ""
  META_ARCHITECTURE: "ProposalClipClassifier"
  MASK_ON: True
  CLIP_ADAPTER:
    PROMPT_LEARNER: "learnable"
    # for learnable prompt
    PROMPT_DIM: 768
    PROMPT_SHAPE: (16, 0)
    #CLIP_MODEL_NAME: "ViT-B/16"
    CLIP_MODEL_NAME: "/mnt/dolphinfs/hdd_pool/docker/user/hadoop-vacv/hancong/code/pretrain/ov-seg/zsseg.baseline/weights/clip/ViT-B-16.pt"
DATASETS:
  TRAIN: ("coco_2017_train_stuff_base_sem_seg_classification",)
  TEST: ("coco_2017_test_stuff_sem_seg_classification",)
  SAMPLE_PER_CLASS: 32
INPUT:
  MIN_SIZE_TRAIN: (336,336)
  MIN_SIZE_TEST: 336
  MAX_SIZE_TEST: 2560
  SIZE_DIVISIBILITY: -1
  FORMAT: "RGB"
  DATASET_MAPPER_NAME: "mask_former_binary_semantic"
SOLVER:
  IMS_PER_BATCH: 32
  TEST_IMS_PER_BATCH: 8
  OPTIMIZER: "SGD"
  BASE_LR: 0.02
  WEIGHT_DECAY: 0.0005
  LR_SCHEDULER_NAME: "WarmupCosineLR"
  WARMUP_METHOD: "constant"  
  WARMUP_FACTOR: 0.005
  WARMUP_ITERS: 100
  # IMS_PER_BATCH: 1
  # TEST_IMS_PER_BATCH: 1
  MAX_ITER: 16000
  CHECKPOINT_PERIOD: 1000
TEST:
  EVAL_PERIOD: 3000
OUTPUT_DIR: "/mnt/dolphinfs/hdd_pool/docker/user/hadoop-vacv/hancong/code/pretrain/ov-seg/zsseg.baseline/output/promptproposal/learnprompt_bs32_10k_4"
