_BASE_: zero_shot_maskformer_R50_bs32_60k.yaml
MODEL:
  META_ARCHITECTURE: "ZeroShotMaskFormerClipfeatUpsample"
  BACKBONE:
    NAME: "build_resnet_deeplab_backbone"
  
  WEIGHTS: "detectron2://DeepLab/R-103.pkl"
  RESNETS:
    DEPTH: 101
    STEM_TYPE: "deeplab"
    STEM_OUT_CHANNELS: 128
    STRIDE_IN_1X1: False
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    # NORM: "SyncBN"
    RES5_MULTI_GRID: [1, 2, 4]
  CLIP_ADAPTER:
    CLIP_ENSEMBLE: True
    CLIP_ENSEMBLE_WEIGHT: 0.8
INPUT:
  MIN_SIZE_TRAIN: !!python/object/apply:eval ["[int(x * 0.1 * 512) for x in range(5, 16)]"]
OUTPUT_DIR: "deop/train_log"
DATASETS:
  
  TEST: ("coco_2017_test_stuff_base_sem_seg", "coco_2017_test_stuff_novel_sem_seg", "coco_2017_test_stuff_sem_seg")
  TEST: ("coco_2017_test_stuff_sem_seg",)
SOLVER:
  IMS_PER_BATCH: 32
  TEST_IMS_PER_BATCH: 8
TEST:
  EVAL_PERIOD: 5000
