_BASE_: zero_shot_maskformer_R50_bs32_60k.yaml
MODEL:
  META_ARCHITECTURE: "ZeroShotClipfeatUpsampleNodecoderSAMMaskNoAssembly"
  BACKBONE:
    NAME: "build_resnet_deeplab_backbone"
  
  WEIGHTS: "detectron2://DeepLab/R-103.pkl"
  # WEIGHTS: "weights/maskfomer/R-103.pkl"
  WEIGHTS: "/mnt/dolphinfs/hdd_pool/docker/user/hadoop-vacv/hancong/code/pretrain/ov-seg/zsseg.baseline/prompt/output0128end2end/R101c_decoder_1layer_vit16_featup_delnorm@decoder_query2D_maskvit_noatten_learnprompt__dice08_bce20_layerPre5_learnposition_addcfg_noend2end_lr02_img512_bat32_1/model_final.pth"
  # WEIGHTS: "/mnt/dolphinfs/hdd_pool/docker/user/hadoop-vacv/hancong/code/pretrain/ov-seg/zsseg.baseline/weights/maskfomer/R-103.pkl"
  RESNETS:
    DEPTH: 101
    STEM_TYPE: "deeplab"
    STEM_OUT_CHANNELS: 128
    STRIDE_IN_1X1: False
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    # NORM: "SyncBN"
    RES5_MULTI_GRID: [1, 2, 4]
  CLIP_ADAPTER:
    CLIP_ENSEMBLE: True
    CLIP_ENSEMBLE_WEIGHT: 0.8
    # PROMPT_LEARNER: "predefined"
    PROMPT_CHECKPOINT: "/mnt/dolphinfs/hdd_pool/docker/user/hadoop-vacv/hancong/code/pretrain/ov-seg/zsseg.baseline/output/promptproposal/learnprompt_bs32_10k_4/model_final.pth"
  MASK_FORMER:
    SAM_POINTS_PER_SIDE: 20
OUTPUT_DIR: "prompt/output0817/R101c_learned_prompt_bs32_60k_newdata"
DATASETS:
  TEST: ("coco_2017_test_stuff_base_sem_seg", "coco_2017_test_stuff_novel_sem_seg", "coco_2017_test_stuff_sem_seg")
  TEST: ("coco_2017_test_stuff_sem_seg",)
  TEST: ("coco_2017_test_stuff_sem_seg_head200",)
SOLVER:
  IMS_PER_BATCH: 32
  TEST_IMS_PER_BATCH: 8
TEST:
  EVAL_PERIOD: 5000

# MODEL.MASK_FORMER.SAM_POINTS_PER_SIDE = 16

